### ISSUE TITLE
Release Henshin 1.4.0

### ISSUE THREAD

**Issue by stefan-ka** [stefan-ka/henshin-maven#1]
Hi there

Nice script and instructions! 

I tried to deploy the latest Henshin version 1.4.0, but I cannot publish into the same Clojars group 'henshin', since I'm not part of that group:

`Failed to deploy artifacts: Could not transfer artifact henshin:henshin:jar:1.4.0 from/to clojars (https://clojars.org/repo/): Access denied to: https://clojars.org/repo/henshin/henshin/1.4.0/henshin-1.4.0.jar, ReasonPhrase: Forbidden - You don't have access to the 'henshin' group.`

Could you please release version 1.4.0 or give me (stefanka) access to the group?
Otherwise I have to deploy the version into a new group...

Thanks!

**Comment by stefan-ka** [comment]
I published the latest version here: https://clojars.org/org.eclipse.emf.henshin/henshin

**Comment by tsdh** [comment]
@stefan-ka Hi Stefan, that's even better.  Do you want to take over the project?  I'm not in academia anymore so there won't be any activity on this project from my side.

**Comment by stefan-ka** [comment]
@tsdh Hi Tassilo. I can take over if you want, although I don't expect much activity from my side as well. But there is a new Henshin version which should be released soon...

**Comment by tsdh** [comment]
@stefan-ka You should have received a transfer request.  Thanks!
